<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-08KK0IC" failures="1" tests="3" name="Test" time="7.906" errors="0" timestamp="2025-02-21T09:27:45 IST">
  <testcase classname="day20.ListenerClass" name="testLogo" time="0.053"/>
  <testcase classname="day20.ListenerClass" name="testAppUrl" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at day20.ListenerClass.testAppUrl(ListenerClass.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testAppUrl -->
  <testcase classname="day20.ListenerClass" name="testHomepageTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testHomepageTitle -->
</testsuite> <!-- Test -->
